#+STYLE: <link rel="stylesheet" type="text/css" href="style.css">
#+STARTUP: indent
#+TITLE: pg-terminal: Window system configuration

Starting in Emacs 23, Emacs handles OS X and other windowing systems as different "terminals." (An abstraction extended -- perhaps too far -- from old-school physical terminals like VT100s, and later virtual terminals like xterm.) More information is available in [[http://www.gnu.org/software/emacs/manual/html_node/elisp/Multiple-Terminals.html#Multiple-Terminals][this section]] and [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Mac-OS-_002f-GNUstep.html#Mac-OS-_002f-GNUstep][this section]] of the Emacs manual.

Emacs provides a single =term-setup-hook=, but having a hook for each terminal/window system enables a more declarative configuration style, so that's what I've implmented here. These hooks correspond to the possible values of =window-system=:

| Hook                | Run when frame is displayed on        |
|---------------------+---------------------------------------|
| =pg-terminal-t-setup-hook=   | A text terminal                       |
| =pg-terminal-x-setup-hook=   | An X GUI terminal                     |
| =pg-terminal-w32-setup-hook= | A Windows GUI terminal                |
| =pg-terminal-ns-setup-hook=  | An OS X GUI terminal                  |
| =pg-terminal-pc-setup-hook=  | An MS-DOS terminal (I'm so, so sorry) |

Each hook will, by default, log itself when it runs, so it's clear which hook is running when.

* Package Header

#+BEGIN_SRC emacs-lisp
  ;;; pg-terminal-config.el --- Window system configuration

  ;; Copyright (C) 2017 Phil Groce

  ;; Author: Phil Groce <pgroce@gmail.com>
  ;; Version: 0.1
  ;; Keywords: gui
#+END_SRC


* Requires

This package has no dependencies.

* Code

#+BEGIN_SRC emacs-lisp

  (defvar pg-terminal-t-setup-hook '()
    "Run in term-setup-hook to customize Emacs run on UNIX text
    terminals (including OS X)")
  (add-hook 'pg-terminal-t-setup-hook
            (lambda () (message "Running pg-terminal-t-setup-hook")))

  (defvar pg-terminal-x-setup-hook '()
    "Run in term-setup-hook to customize Emacs run on UNIX
    X-Windows (including OS X?)")
  (add-hook 'pg-terminal-t-setup-hook
            (lambda () (message "Running pg-terminal-x-setup-hook")))

  (defvar pg-terminal-w32-setup-hook '()
    "Run in term-setup-hook to customize Emacs run on
    Windows (GUI)")
  (add-hook 'pg-terminal-t-setup-hook
            (lambda () (message "Running pg-terminal-w32-setup-hook")))

  (defvar pg-terminal-ns-setup-hook '()
    "Run in term-setup-hook to customize Emacs run on OS
    X (GUI)")
  (add-hook 'pg-terminal-t-setup-hook
            (lambda () (message "Running pg-terminal-ns-setup-hook")))

  (defvar pg-terminal-pc-setup-hook '()
    "Run in term-setup-hook to customize Emacs run on Windows
    text terminals (so-called \"DOS terminals\".)")
  (add-hook 'pg-terminal-t-setup-hook
            (lambda () (message "Running pg-terminal-pc-setup-hook")))

  (add-hook 'term-setup-hook
            (lambda ()
              (case window-system
                ('t (run-hooks 'pg-terminal-t-setup-hook))
                ('x (run-hooks 'pg-terminal-x-setup-hook))
                ('w32 (run-hooks 'pg-terminal-w32-setup-hook))
                ('ns (run-hooks 'pg-terminal-ns-setup-hook))
                ('pc (run-hooks 'pg-terminal-pc-setup-hook)))))
#+END_SRC

* Provides

#+BEGIN_SRC emacs-lisp
  (provide 'pg-terminal-config)
  ;;; pg-terminal-config.el ends here
#+END_SRC
